version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tguard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bot:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./config.toml:/app/config.toml
    command: python -m src.bot.main
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "python -c \"import sys; sys.exit(0)\"" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "17985:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./config.toml:/app/config.toml
    command: python -m src.api.main
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=5)\"" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
