version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tguard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./config.toml:/app/config.toml
      - ./logs:/app/logs
    command: python -m src.bot.main
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "ps aux | grep 'python -m src.bot.main' | grep -v grep || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "17985:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./config.toml:/app/config.toml
      - ./logs:/app/logs
      - ./static:/app/static
    command: python -m src.api.main
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
